name: Add SLR Entry
description: Submit a new study for inclusion in the SLR
title: "[SLR Entry] "
labels: ["slr-entry"]
body:
  - type: input
    id: doi
    attributes:
      label: DOI
      placeholder: "10.5281/zenodo.XXXXXXX"
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      options:
        - Cloud
        - General Purpose
        - Cyber-Physical Systems
        - Systems of Systems
        - Operational Technologies
        - Open Systems Architecture
        - Internet of Things
    validations:
      required: true

  - type: dropdown
    id: trl
    attributes:
      label: TRL
      options:
        - "1-3"
        - "4-6"
        - "7-9"
        - "NA"
    validations:
      required: true

  - type: dropdown
    id: ai
    attributes:
      label: AI-based
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: targeted_threats
    attributes:
      label: Targeted Threats
      multiple: true
      options:
        - S (Spoofing)
        - T (Tampering)
        - R (Repudiation)
        - I (Information Disclosure)
        - D (Denial of Service)
        - E (Elevation of Privilege)
        - "NA"
    validations:
      required: true

  - type: dropdown
    id: attack_scenarios
    attributes:
      label: Attack Scenarios
      multiple: true
      options:
        - "T1 (Disable functionality or system elements)"
        - "T2 (Manipulation of configuration)"
        - "T3 (Credentials misuse)"
        - "T4 (Various Denial of Service (DoS) injections)"
        - "T5 (Data and resource injections)"
        - "T6 (Environment-related)"
        - "NA"
    validations:
      required: true

  - type: dropdown
    id: evaluation_method
    attributes:
      label: Evaluation Method
      multiple: true
      options:
        - Empirical
        - Analytical
        - Simulation
        - "NA"
    validations:
      required: true
