name: Add SLR Entry
description: Submit a new study for inclusion in the SLR
title: "[SLR Entry] "
labels: ["slr-entry"]
body:
  - type: input
    id: study
    attributes:
      label: Study ID
      description: e.g. `torkura_cloudstrike_2020`
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year
    validations:
      required: true

  - type: input
    id: domain
    attributes:
      label: Domain
    validations:
      required: true

  - type: input
    id: trl
    attributes:
      label: TRL
    validations:
      required: true

  - type: dropdown
    id: ai
    attributes:
      label: AI-based
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: targeted_threats
    attributes:
      label: Targeted Threats
    validations:
      required: true

  - type: textarea
    id: attack_scenarios
    attributes:
      label: Attack Scenarios
    validations:
      required: true

  - type: textarea
    id: evaluation_method
    attributes:
      label: Evaluation Method
    validations:
      required: true
